### ISSUE TITLE
js/console.log, println, etc. don't show output with node REPL

### ISSUE THREAD

**Issue by noprompt** [cemerick/piggieback#41]
Here's a snapshot of my REPL session demonstrating the problem.

```
user> (cemerick.piggieback/cljs-repl
 :repl-env (node/repl-env)
 :output-dir ".cljs_node_repl"
 :cache-analysis true
 :source-map true)
Type `:cljs/quit` to stop the ClojureScript REPL
nil
cljs.user> (println "hello")
nil
cljs.user> (js/console.log "hello")
nil
```

**Comment by cemerick** [comment]
I'm guessing you're using emacs or something. :-)

The node REPL env is set up to print using the `util.print` function in node (https://github.com/clojure/clojurescript/blob/master/src/clj/cljs/repl/node.clj#L151), so your printlns are being dumped to stdout. If you're using your REPL from emacs (or any other non-terminal nREPL client), that means you're not going to see things printed in your REPL window (look for it in the `*nrepl-server*` buffer in emacs, or its analogue in other tools). _This isn't a problem as long as you're at a terminal, e.g. if you use `lein repl` directly._

Making it so that printed output is displayed inline with evaluation results for all nREPL clients is going to require patching around default REPL environment behaviour similar to what is done for Rhino (https://github.com/cemerick/piggieback/blob/master/src/cemerick/piggieback.clj#L156). It won't be as easy as it is in Rhino though, as there we just pass along `*out*` within the same JVM. What you really want is something akin to browser-REPL-like printed content queuing; that'll be very tough to add in without significantly modifying the Node REPL env impl.  I see a couple of possible hacks:

* hook `cljs.repl.node/setup` to set `*print-fn*` to one that throws the printed output in an exception with a fixed prefix message that piggieback looks for in `cljs-eval`
* wrap all evaluations with a binding of `*print-fn*` that gathers all output from the wrapped expression, and returns it in a map along with the expression's result (again, to be recognized by `cljs-eval` and separated again).
* hook `cljs.repl.node/setup` to set `*print-fn*` to one that gathers printed output into a vector + transparently "ping" node with evaluations to drain that vector every NNN millis. 

I'm open to other ideas; only the last of the above seems like something I'd be willing to merge, and even that is pretty bleak (though perhaps better than having someone maintain an nREPL-only Node REPL env impl).

**Comment by cemerick** [comment]
Fixing this would actually be pretty easy. Instead of having the node process `cljs.repl.node` starts inherit the JVM's stdout/err, just pump content from the created process' stdout/err to `*out*` and `*err*` using `java.io.PipedReader` et al. Should Just Work.

**Comment by cemerick** [comment]
http://dev.clojure.org/jira/browse/CLJS-1176

**Comment by cemerick** [comment]
This is now fixed on ClojureScript master.
