### ISSUE TITLE
(ns) does not load refered namespaces

### ISSUE THREAD

**Issue by gdanov** [cemerick/piggieback#49]
running nodejs repl in lein repl as described in the tutorial everything works as expected until I start using ```ns```

this code
```
(ns repl.two
	(:require [clojure.string :as ss])
	)

(defn two []
	(println "two++!!")
	(println (ss/split-lines "one\ntwo")))

(println (namespace ::x))
```
dumps ```repl.two``` which shows that the function is defined in the right namespace. Next
```
(two)
;or
(in-ns 'cljs.user)
(repl.two/two)
```
both throw ```ExceptionInfo ReferenceError: clojure is not defined```

when I execute this
```
(require '[clojure.string] :reload)
```
the function gets operational

using lein@2.5.1 which uses nREPL 0.2.6
com.cemerick/piggieback@"0.1.5"

**Comment by cemerick** [comment]
The work on the `new-cljs-repl` branch, currently available in `0.2.0-SNAPSHOT`, is effectively a rewrite due to the new ClojureScript REPL API, etc. Closing all issues filed against `0.1.x`; most (or all) of them should be resolved and/or irrelevant. If you hit this problem when using a build in the `0.2.x` series, please comment here, or open a new ticket.
