### ISSUE TITLE
`wrap-cljs-repl` now expects `pr-values`

### ISSUE THREAD

**Issue by cichli** [cemerick/piggieback#51]
Continuing on from the discussion in the line notes of 7eb5e1ebdb497facbea1278efb5915a31c00152d:

The inspector middleware in CIDER makes use of the `:transport` slot to capture the `:value` slot of eval responses. This means it needs to:

* expect `wrap-cljs-repl` and `eval`, so it can inject the transport before the eval response is sent
* require `pr-values`, so the transport it adds wraps that of `pr-values`

Because `wrap-cljs-repl` now expects `pr-values`, this results in an unsatisfiable set of dependencies.

**Comment by cemerick** [comment]
OK, so the inspector middleware is wanting to deal with Clojure _values_ in `:value`, before they're `pr-str`'d. That is not going to be portable. ClojureScript REPLs have always only provided string return "values", as that's what can come over the transom from the REPL environments. Piggieback currently / used to do this dance of attempting to read that string in order to deliver a _Clojure_ value in `:value`, and bail if that wasn't possible:

https://github.com/cemerick/piggieback/blob/master/src/cemerick/piggieback.clj#L123

I'm not going to do that anymore, as that just complicated things even more in different ways, and obscured certain nasty error conditions. It's especially not warranted now that Piggieback isn't directly reusing the evaluation machinery in `interruptible-eval` (except for the interrupt stuffs).

Note that `pr-values` is technically an implementation detail, a precursor to what I was planning on offering to support pluggable pretty-printing, etc. (i.e. it's not listed [here](https://github.com/clojure/tools.nrepl/blob/master/doc/ops.md), and you'll notice that `:value` there for the `eval` op is described as a string that is "often `read`able".

For any middleware that wants to work with `:value` results as _values_, the same try-to-read strategy can be adopted when the session is ClojureScript-flavoured. That should restore the current state of affairs, but local to said middleware.

This makes me wonder if various `eval` handlers should pass along a "language context" slot in their result, indicating Clojure/ClojureScript/???, so that later processing doesn't have to go rooting around in the session map.

**Comment by cichli** [comment]
Hmm, so if I want to provide the same set of inspector ops for both Clojure and ClojureScript - should I just have two separate handlers?

* one that expects `eval` and requires `pr-values`, and only does anything if piggieback is not active
* one that expects `wrap-cljs-repl`, and only does anything if piggieback is active

**Comment by cemerick** [comment]
It sounds pretty bleak when you put it that way, huh? :-(

Could you link me to the middleware in question, so I can better understand its requirements?

**Comment by cichli** [comment]
Sure thing, see [here](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/inspect.clj).

**Comment by cichli** [comment]
I can confirm the two-handler solution works but adds a bit of manual boilerplate. Not ideal, and it would take a something a bit more clever than what I've done (just the opposite condition in each handler) to support N langs, but it's workable.

How about modifying `pr-values` to check for some option in the message being sent - piggieback would set this to false in the response it sends from the `:print` function passed to `cljs.repl/repl*`. Basically a way of signalling "hey, I'm sending a `:value` slot, but it's already printed readably".

The language context is interesting, and definitely beats checking if piggieback has a dynamic var bound in the session map when we're checking an eval response - but for all the completion/documentation lookup ops, we need to grab piggieback's compiler env from the session map anyway for the data it contains.

**Comment by cemerick** [comment]
Yeah, pr-values need modifying. In the end, I'd like for it to go away entirely, but one step at a time. Look for more updates tomorrow.

**Comment by cemerick** [comment]
`wrap-cljs-repl` no longer expects `pr-values` as of the latest `0.2.0-SNAPSHOT`, and the `:value` responses it produces have a `:printed-value` "flag" as discussed, which `pr-values` checks to avoid re-printing.

I think this should simplify your middleware setup?

**Comment by cichli** [comment]
Yeah, that sounds right. I'll give it a go this evening, thanks a lot!

btw, doing the try-to-read bit in cider-nrepl is fine by me - but we need to do it only for piggieback 0.2.x. Right now the way I determine if we're using 0.2.x or 0.1.x is by trying to resolve `*cljs-compiler-env*`. The fact that it's a bit of a hack doesn't bother me too much as we won't support 0.1.x forever, but if there's a more sane way to do it I'm all ears :-).

**Comment by cemerick** [comment]
That sort of feature-sniffing is fairly sane. Also be aware that all Leiningen-packaged artifacts contain useful bits in META-INF, including e.g. `META-INF/maven/com.cemerick/piggieback/pom.properties`:

```
#Leiningen
#Thu Mar 26 07:14:46 EDT 2015
version=0.2.0-SNAPSHOT
revision=586063ed7236386ec1393ca9d81b911732ca7ede\n
groupId=com.cemerick
artifactId=piggieback
```
