### ISSUE TITLE
Empty persistent vector for special functions

### ISSUE THREAD

**Issue by mfikes** [cemerick/piggieback#53]
When I evaluate a REPL special function, it appears that an empty persistent vector is being returned, and this ultimately causes Cursive to complain.

I'm using Ambly with Piggieback, and if I simply use it in `lein repl`, I see the following behavior (the same holds for `require` and `load-file`):
```
cljs.user=> (in-ns 'foo.bar)
[]
foo.bar=> (in-ns 'foo.baz)
[]
foo.baz=>
```

(Normally, the REPL prints `nil` for special functions.)

Here is what occurs in Cursive:
```
(in-ns 'foo.bar)
=> Error handling response - class java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to java.lang.CharSequence
```

None of this appears to break any functionality. (For example, `require` actually works, etc.)

(To run this, I'm setting up Ambly using instructions at https://github.com/omcljs/ambly/wiki/REPL-in-Cursive)

Note: In Cursive, I've been typing these special functions directly into the box in the lower-right of Cursive---the REPL input area---as opposed to using menus.

**Comment by cemerick** [comment]
The fix for this brings piggieback closer to how `interruptible-eval` works w/ Clojure (always responding with `:value "nil"` when an evaluated expression has no return) w.r.t. ClojureScript's cljs.repl special functions. The vector printing in Leiningen is gone now (replaced by the expected `nil` printing), so I hope Cursive's issue will disappear.

Leaving this open pending confirmation of the latter. A new `0.2.0-SNAPSHOT` has been delivered. /cc @cursiveclojure.

**Comment by mfikes** [comment]
I can confirm that the issues documented in the original description are now fixed.

**Comment by cemerick** [comment]
Great, thanks for the verification!
